JAVAC=javac -Xlint:none
FULL_CLASSPATH=.
CLASSES= jode/bytecode/Reference.class \
        jode/bytecode/GrowableConstantPool.class \
        jode/bytecode/Handler.class \
        jode/bytecode/FieldInfo.class \
        jode/bytecode/BytecodeInfo.class \
        jode/bytecode/ConstantPool.class \
        jode/bytecode/TypeSignature.class \
        jode/bytecode/InnerClassInfo.class \
        jode/bytecode/BinaryInfo.class \
        jode/bytecode/Opcodes.class \
        jode/bytecode/MethodInfo.class \
        jode/bytecode/ClassInfo.class \
        jode/bytecode/SearchPath.class \
        jode/bytecode/ClassFormatException.class \
        jode/bytecode/Instruction.class \
        jode/bytecode/LocalVariableInfo.class \
        jode/bytecode/LineNumber.class \
        jode/GlobalOptions.class \
        jode/flow/JsrBlock.class \
        jode/flow/SequentialBlock.class \
        jode/flow/CombineIfGotoExpressions.class \
        jode/flow/FinallyBlock.class \
        jode/flow/CreatePrePostIncExpression.class \
        jode/flow/SpecialBlock.class \
        jode/flow/BreakBlock.class \
        jode/flow/LoopBlock.class \
        jode/flow/CreateAssignExpression.class \
        jode/flow/CreateCheckNull.class \
        jode/flow/VariableStack.class \
        jode/flow/TransformExceptionHandlers.class \
        jode/flow/VariableSet.class \
        jode/flow/CreateNewConstructor.class \
        jode/flow/ContinueBlock.class \
        jode/flow/ConditionalBlock.class \
        jode/flow/ReturnBlock.class \
        jode/flow/RetBlock.class \
        jode/flow/IfThenElseBlock.class \
        jode/flow/CreateConstantArray.class \
        jode/flow/SynchronizedBlock.class \
        jode/flow/InstructionBlock.class \
        jode/flow/CreateIfThenElseOperator.class \
        jode/flow/CaseBlock.class \
        jode/flow/ThrowBlock.class \
        jode/flow/TryBlock.class \
        jode/flow/Jump.class \
        jode/flow/InstructionContainer.class \
        jode/flow/CompleteSynchronized.class \
        jode/flow/DescriptionBlock.class \
        jode/flow/SwitchBlock.class \
        jode/flow/EmptyBlock.class \
        jode/flow/CreateForInitializer.class \
        jode/flow/CatchBlock.class \
        jode/flow/CreateExpression.class \
        jode/flow/BreakableBlock.class \
        jode/flow/FlowBlock.class \
        jode/flow/CreateClassField.class \
        jode/flow/StructuredBlock.class \
        jode/flow/TransformConstructors.class \
        jode/flow/SlotSet.class \
        jode/jvm/SimpleRuntimeEnvironment.class \
        jode/jvm/InterpreterException.class \
        jode/jvm/VerifyException.class \
        jode/jvm/CodeVerifier.class \
        jode/jvm/NewObject.class \
        jode/jvm/RuntimeEnvironment.class \
        jode/jvm/Value.class \
        jode/jvm/SyntheticAnalyzer.class \
        jode/jvm/Interpreter.class \
        jode/obfuscator/CodeAnalyzer.class \
        jode/obfuscator/MethodIdentifier.class \
        jode/obfuscator/Main.class \
        jode/obfuscator/TranslationTable.class \
        jode/obfuscator/ScriptParser.class \
        jode/obfuscator/ParseException.class \
        jode/obfuscator/LocalIdentifier.class \
        jode/obfuscator/IdentifierMatcher.class \
        jode/obfuscator/Renamer.class \
        jode/obfuscator/ClassIdentifier.class \
        jode/obfuscator/PackageIdentifier.class \
        jode/obfuscator/ClassBundle.class \
        jode/obfuscator/modules/ModifierMatcher.class \
        jode/obfuscator/modules/NameSwapper.class \
        jode/obfuscator/modules/ConstantAnalyzer.class \
        jode/obfuscator/modules/WildCard.class \
        jode/obfuscator/modules/KeywordRenamer.class \
        jode/obfuscator/modules/StrongRenamer.class \
        jode/obfuscator/modules/SimpleAnalyzer.class \
        jode/obfuscator/modules/MultiIdentifierMatcher.class \
        jode/obfuscator/modules/SerializePreserver.class \
        jode/obfuscator/modules/LocalOptimizer.class \
        jode/obfuscator/modules/UniqueRenamer.class \
        jode/obfuscator/modules/RemovePopAnalyzer.class \
        jode/obfuscator/CodeTransformer.class \
        jode/obfuscator/OptionHandler.class \
        jode/obfuscator/ConstantRuntimeEnvironment.class \
        jode/obfuscator/Identifier.class \
        jode/obfuscator/FieldIdentifier.class \
        jode/decompiler/OuterValues.class \
        jode/decompiler/Analyzer.class \
        jode/decompiler/ClassDeclarer.class \
        jode/decompiler/Window.class \
        jode/decompiler/Main.class \
        jode/decompiler/TabbedPrintWriter.class \
        jode/decompiler/ClassAnalyzer.class \
        jode/decompiler/Options.class \
        jode/decompiler/LocalVariableRangeList.class \
        jode/decompiler/LocalVariableTable.class \
        jode/decompiler/MethodAnalyzer.class \
        jode/decompiler/ProgressListener.class \
        jode/decompiler/Declarable.class \
        jode/decompiler/OuterValueListener.class \
        jode/decompiler/Decompiler.class \
        jode/decompiler/Scope.class \
        jode/decompiler/LocalInfo.class \
        jode/decompiler/Opcodes.class \
        jode/decompiler/DeadCodeAnalysis.class \
        jode/decompiler/LocalVarEntry.class \
        jode/decompiler/Applet.class \
        jode/decompiler/ImportHandler.class \
        jode/decompiler/FieldAnalyzer.class \
        jode/AssertError.class \
        jode/util/SimpleSet.class \
        jode/util/SimpleMap.class \
        jode/util/ArrayEnum.class \
        jode/util/UnifyHash.class \
        jode/type/MethodType.class \
        jode/type/NullType.class \
        jode/type/ArrayType.class \
        jode/type/ReferenceType.class \
        jode/type/RangeType.class \
        jode/type/IntegerType.class \
        jode/type/ClassInterfacesType.class \
        jode/type/Type.class \
        jode/expr/NewOperator.class \
        jode/expr/NopOperator.class \
        jode/expr/CheckCastOperator.class \
        jode/expr/CompareToIntOperator.class \
        jode/expr/ClassFieldOperator.class \
        jode/expr/Expression.class \
        jode/expr/InstanceOfOperator.class \
        jode/expr/NewArrayOperator.class \
        jode/expr/ConstantArrayOperator.class \
        jode/expr/GetFieldOperator.class \
        jode/expr/ArrayLoadOperator.class \
        jode/expr/InvokeOperator.class \
        jode/expr/LocalLoadOperator.class \
        jode/expr/SimpleOperator.class \
        jode/expr/PrePostFixOperator.class \
        jode/expr/MonitorEnterOperator.class \
        jode/expr/CheckNullOperator.class \
        jode/expr/UnaryOperator.class \
        jode/expr/LocalVarOperator.class \
        jode/expr/PopOperator.class \
        jode/expr/ConstOperator.class \
        jode/expr/MonitorExitOperator.class \
        jode/expr/PutFieldOperator.class \
        jode/expr/ConvertOperator.class \
        jode/expr/Operator.class \
        jode/expr/FieldOperator.class \
        jode/expr/OuterLocalOperator.class \
        jode/expr/LocalStoreOperator.class \
        jode/expr/ThisOperator.class \
        jode/expr/BinaryOperator.class \
        jode/expr/StringAddOperator.class \
        jode/expr/LValueExpression.class \
        jode/expr/ArrayStoreOperator.class \
        jode/expr/CompareBinaryOperator.class \
        jode/expr/ArrayLengthOperator.class \
        jode/expr/IfThenElseOperator.class \
        jode/expr/ShiftOperator.class \
        jode/expr/CombineableOperator.class \
        jode/expr/NoArgOperator.class \
        jode/expr/MatchableOperator.class \
        jode/expr/IIncOperator.class \
        jode/expr/StoreInstruction.class \
        jode/expr/CompareUnaryOperator.class \
        test/HintTypeTest.class \
        test/MethodScopedClass.class \
        test/Expressions.class \
        test/AnonymousClass.class \
        test/InnerClass.class \
        test/InlinedAnon.class \
        test/IfCombine.class \
        test/InnerCompat.class \
        test/NestedAnon.class \
        test/Unreach.class \
        test/LocalTypes.class \
        test/JavacBug.class \
        test/ConstantTypes.class \
        test/PrivateHideTest.class \
        test/TryCatch.class \
        test/For.class \
        test/ClassOpTest.class \
        test/Flow.class \
        test/TriadicExpr.class \
        test/ArrayCloneTest.class \
        test/ArrayTest.class \
        test/OptimizerTest.class \
        test/AnonymousJavac.class \
        test/AssignOp.class \
        gnu/getopt/GetoptDemo.class \
        gnu/getopt/Getopt.class \
        gnu/getopt/LongOpt.class \

#        test/InlineTest.class \
#        test/OptimizeTest.class \

#        test/ResolveConflicts.class \
#        test/CountOpcodes.class \
#        jode/swingui/Main.class \
#        jode/swingui/HierarchyTreeModel.class \
#        jode/swingui/PackagesTreeModel.class \

JAVAS= jode/bytecode/Reference.java \
        jode/bytecode/GrowableConstantPool.java \
        jode/bytecode/Handler.java \
        jode/bytecode/FieldInfo.java \
        jode/bytecode/BytecodeInfo.java \
        jode/bytecode/ConstantPool.java \
        jode/bytecode/TypeSignature.java \
        jode/bytecode/InnerClassInfo.java \
        jode/bytecode/BinaryInfo.java \
        jode/bytecode/Opcodes.java \
        jode/bytecode/MethodInfo.java \
        jode/bytecode/ClassInfo.java \
        jode/bytecode/SearchPath.java \
        jode/bytecode/ClassFormatException.java \
        jode/bytecode/Instruction.java \
        jode/bytecode/LocalVariableInfo.java \
        jode/bytecode/LineNumber.java \
        jode/GlobalOptions.java \
        jode/flow/JsrBlock.java \
        jode/flow/SequentialBlock.java \
        jode/flow/CombineIfGotoExpressions.java \
        jode/flow/FinallyBlock.java \
        jode/flow/CreatePrePostIncExpression.java \
        jode/flow/SpecialBlock.java \
        jode/flow/BreakBlock.java \
        jode/flow/LoopBlock.java \
        jode/flow/CreateAssignExpression.java \
        jode/flow/CreateCheckNull.java \
        jode/flow/VariableStack.java \
        jode/flow/TransformExceptionHandlers.java \
        jode/flow/VariableSet.java \
        jode/flow/CreateNewConstructor.java \
        jode/flow/ContinueBlock.java \
        jode/flow/ConditionalBlock.java \
        jode/flow/ReturnBlock.java \
        jode/flow/RetBlock.java \
        jode/flow/IfThenElseBlock.java \
        jode/flow/CreateConstantArray.java \
        jode/flow/SynchronizedBlock.java \
        jode/flow/InstructionBlock.java \
        jode/flow/CreateIfThenElseOperator.java \
        jode/flow/CaseBlock.java \
        jode/flow/ThrowBlock.java \
        jode/flow/TryBlock.java \
        jode/flow/Jump.java \
        jode/flow/InstructionContainer.java \
        jode/flow/CompleteSynchronized.java \
        jode/flow/DescriptionBlock.java \
        jode/flow/SwitchBlock.java \
        jode/flow/EmptyBlock.java \
        jode/flow/CreateForInitializer.java \
        jode/flow/CatchBlock.java \
        jode/flow/CreateExpression.java \
        jode/flow/BreakableBlock.java \
        jode/flow/FlowBlock.java \
        jode/flow/CreateClassField.java \
        jode/flow/StructuredBlock.java \
        jode/flow/TransformConstructors.java \
        jode/flow/SlotSet.java \
        jode/jvm/SimpleRuntimeEnvironment.java \
        jode/jvm/InterpreterException.java \
        jode/jvm/VerifyException.java \
        jode/jvm/CodeVerifier.java \
        jode/jvm/NewObject.java \
        jode/jvm/RuntimeEnvironment.java \
        jode/jvm/Value.java \
        jode/jvm/SyntheticAnalyzer.java \
        jode/jvm/Interpreter.java \
        jode/obfuscator/CodeAnalyzer.java \
        jode/obfuscator/MethodIdentifier.java \
        jode/obfuscator/Main.java \
        jode/obfuscator/TranslationTable.java \
        jode/obfuscator/ScriptParser.java \
        jode/obfuscator/ParseException.java \
        jode/obfuscator/LocalIdentifier.java \
        jode/obfuscator/IdentifierMatcher.java \
        jode/obfuscator/Renamer.java \
        jode/obfuscator/ClassIdentifier.java \
        jode/obfuscator/PackageIdentifier.java \
        jode/obfuscator/ClassBundle.java \
        jode/obfuscator/modules/ModifierMatcher.java \
        jode/obfuscator/modules/NameSwapper.java \
        jode/obfuscator/modules/LocalizeFieldTransformer.java \
        jode/obfuscator/modules/ConstantAnalyzer.java \
        jode/obfuscator/modules/WildCard.java \
        jode/obfuscator/modules/KeywordRenamer.java \
        jode/obfuscator/modules/StrongRenamer.java \
        jode/obfuscator/modules/SimpleAnalyzer.java \
        jode/obfuscator/modules/MultiIdentifierMatcher.java \
        jode/obfuscator/modules/SerializePreserver.java \
        jode/obfuscator/modules/LocalOptimizer.java \
        jode/obfuscator/modules/UniqueRenamer.java \
        jode/obfuscator/modules/RemovePopAnalyzer.java \
        jode/obfuscator/CodeTransformer.java \
        jode/obfuscator/OptionHandler.java \
        jode/obfuscator/ConstantRuntimeEnvironment.java \
        jode/obfuscator/Identifier.java \
        jode/obfuscator/FieldIdentifier.java \
        jode/decompiler/OuterValues.java \
        jode/decompiler/Analyzer.java \
        jode/decompiler/ClassDeclarer.java \
        jode/decompiler/Window.java \
        jode/decompiler/Main.java \
        jode/decompiler/TabbedPrintWriter.java \
        jode/decompiler/ClassAnalyzer.java \
        jode/decompiler/Options.java \
        jode/decompiler/LocalVariableRangeList.java \
        jode/decompiler/LocalVariableTable.java \
        jode/decompiler/MethodAnalyzer.java \
        jode/decompiler/ProgressListener.java \
        jode/decompiler/Declarable.java \
        jode/decompiler/OuterValueListener.java \
        jode/decompiler/Decompiler.java \
        jode/decompiler/Scope.java \
        jode/decompiler/LocalInfo.java \
        jode/decompiler/Opcodes.java \
        jode/decompiler/DeadCodeAnalysis.java \
        jode/decompiler/LocalVarEntry.java \
        jode/decompiler/Applet.java \
        jode/decompiler/ImportHandler.java \
        jode/decompiler/FieldAnalyzer.java \
        jode/AssertError.java \
        jode/util/SimpleSet.java \
        jode/util/SimpleMap.java \
        jode/util/ArrayEnum.java \
        jode/util/UnifyHash.java \
        jode/type/MethodType.java \
        jode/type/NullType.java \
        jode/type/ArrayType.java \
        jode/type/ReferenceType.java \
        jode/type/RangeType.java \
        jode/type/IntegerType.java \
        jode/type/ClassInterfacesType.java \
        jode/type/Type.java \
        jode/expr/NewOperator.java \
        jode/expr/NopOperator.java \
        jode/expr/CheckCastOperator.java \
        jode/expr/CompareToIntOperator.java \
        jode/expr/ClassFieldOperator.java \
        jode/expr/Expression.java \
        jode/expr/InstanceOfOperator.java \
        jode/expr/NewArrayOperator.java \
        jode/expr/ConstantArrayOperator.java \
        jode/expr/GetFieldOperator.java \
        jode/expr/ArrayLoadOperator.java \
        jode/expr/InvokeOperator.java \
        jode/expr/LocalLoadOperator.java \
        jode/expr/SimpleOperator.java \
        jode/expr/PrePostFixOperator.java \
        jode/expr/MonitorEnterOperator.java \
        jode/expr/CheckNullOperator.java \
        jode/expr/UnaryOperator.java \
        jode/expr/LocalVarOperator.java \
        jode/expr/PopOperator.java \
        jode/expr/ConstOperator.java \
        jode/expr/MonitorExitOperator.java \
        jode/expr/PutFieldOperator.java \
        jode/expr/ConvertOperator.java \
        jode/expr/Operator.java \
        jode/expr/FieldOperator.java \
        jode/expr/OuterLocalOperator.java \
        jode/expr/LocalStoreOperator.java \
        jode/expr/ThisOperator.java \
        jode/expr/BinaryOperator.java \
        jode/expr/StringAddOperator.java \
        jode/expr/LValueExpression.java \
        jode/expr/ArrayStoreOperator.java \
        jode/expr/CompareBinaryOperator.java \
        jode/expr/ArrayLengthOperator.java \
        jode/expr/IfThenElseOperator.java \
        jode/expr/ShiftOperator.java \
        jode/expr/CombineableOperator.java \
        jode/expr/NoArgOperator.java \
        jode/expr/MatchableOperator.java \
        jode/expr/IIncOperator.java \
        jode/expr/StoreInstruction.java \
        jode/expr/CompareUnaryOperator.java \
        test/HintTypeTest.java \
        test/MethodScopedClass.java \
        test/Expressions.java \
        test/AnonymousClass.java \
        test/InnerClass.java \
        test/InlinedAnon.java \
        test/IfCombine.java \
        test/InlineTest.java \
        test/CountOpcodes.java \
        test/InnerCompat.java \
        test/ResolveConflicts.java \
        test/OptimizeTest.java \
        test/NestedAnon.java \
        test/Unreach.java \
        test/LocalTypes.java \
        test/JavacBug.java \
        test/ConstantTypes.java \
        test/PrivateHideTest.java \
        test/TryCatch.java \
        test/For.java \
        test/ClassOpTest.java \
        test/Flow.java \
        test/TriadicExpr.java \
        test/ArrayCloneTest.java \
        test/ArrayTest.java \
        test/OptimizerTest.java \
        test/AnonymousJavac.java \
        test/AssignOp.java \
        gnu/getopt/GetoptDemo.java \
        gnu/getopt/Getopt.java \
        gnu/getopt/LongOpt.java \

#        jode/obfuscator/modules/LocalizeFieldTransformer.class \
#        jode/swingui/Main.java \
#        jode/swingui/HierarchyTreeModel.java \
#        jode/swingui/PackagesTreeModel.java \

all: $(CLASSES)

#	$(JAVAC) -classpath $(FULL_CLASSPATH) $(JAVAS)

clean:
	rm -f $(CLASSES)

%.class: %.java
	$(JAVAC) -classpath $(FULL_CLASSPATH)  $<
